### ISSUE TITLE
NSSecureCoding doesn't seem to work

### ISSUE THREAD

**Issue by Heruabollo** [macmade/OBJCXX#17] opened 2017-12-05 13:10 UTC
Windows version: Windows 10 Education
Visual studio version: Visual studio Enterprise 2015
Build in 32-bits

I tested the OBJCXX-Test test to see if the NSSecureCoding protocol worked, but when I use the NSKeyedArchiver::archivedDataWithRootObject method then I printed the binary data, the data doesn't seem to be encoded.

Any Idea ?

Thanks :),

Heru.

**Comment by macmade** [comment] 2017-12-05 14:12
Well, difficult to tell without seeing your code or the encoded data.

Please provide more info.

**Comment by Heruabollo** [comment] 2017-12-05 14:21
The only code I use is the one which is provided from the OBJCXX-Test repository, the Foo class on Foo.cpp file.
I just printed the bplist made by the NS::KeyedArchiver::archivedDataWithRootObject method:

`
       
        NS::Log( "%@", static_cast< id >( f1.text() ) );
        f1.text( "hello, universe" );
        NS::Log( "%@", static_cast< id >( f1.text() ) );
        
        d = NS::KeyedArchiver::archivedDataWithRootObject( f1 );
        // Just added a pretty printer here to see what is inside 'd' like: PrettyPrint(d.bytes(), d.length()); 
        NS::Log( "%@", static_cast< id >( d ) );
        
        f2 = NS::KeyedUnarchiver::unarchiveObjectWithData( d );
        
        NS::Log( "%@", static_cast< id >( f2.text() ) );
`

And it's like the NSSecureEncoding has not done its job because the data is has not been encoded :( !

**Comment by macmade** [comment] 2017-12-05 14:52
I don't see any issue in the latest version.

Output should be like:

```
2017-12-05 15:49:16.430 Test.exe[6752:161c] hello, universe
2017-12-05 15:49:16.438 Test.exe[6752:161c] <62706c69 73743030 d4010203 04050817 18542474 6f705824 6f626a65 63747358 24766572 73696f6e 59246172 63686976 6572d106 0754726f 6f748001 a4090a0f 1055246e 756c6cd2 0b0c0d0e 5624636c 61737354 74657874 80038002 5f100f68 656c6c6f 2c20756e 69766572 7365d211 12131658 24636c61 73736573 5a24636c 6173736e 616d65a2 14155346 6f6f584e 534f626a 65637453 466f6f12 000186a0 5f100f4e 534b6579 65644172 63686976 65720811 161f2832 353a3c41 474c5358 5a5c6e73 7c878a8e 979ba000 00000000 00010100 00000000 00001900 00000000 00000000 00000000 0000b2>
2017-12-05 15:49:16.448 Test.exe[6752:161c] hello, universe
```

Data is generated, and the object is unarchived successfully.

What do you mean by «_the data is has not been encoded_»?  
Is the data empty?

**Comment by Heruabollo** [comment] 2017-12-05 15:07
The data is unarchived successfully but inside the bplist generated by NSKeyedArchiver, the string "hello, universe" is not encoded.
I mean, when I binary print the content of the variable d, I can see the string "hello, universe" but I think it should be encoded thanks to the protocol "NSSecureEncoding" and the instance method "encodeWithCoder:" so we shouldn't be able to see this string clearly, but on another format like, for example: "bTCk1J32S+Syd4d87gciwy==".

Sorry if I'm not clear when I'm talking, I hope you understood what I'm talking about :) !

**Comment by macmade** [comment] 2017-12-05 15:16
Well, it looks like you don't understand what `NSSecureCoding` is about.  
It has nothing to do with data representation, or encryption.

It's simply a contract between you and the archiver.  
It simply tells the archiver you are going to decode your properties in a safe manner.

**Implementing `NSSecureCoding` will have zero impact on the generated data, and this is the normal/expected behaviour.**

You can read more on Apple's website:
https://developer.apple.com/documentation/foundation/nssecurecoding

I'm closing this issue, as the code is behaving as expected regarding `NSSecureCoding`.  
Feel free to open another one if you have implementation issues.

**Closed by macmade** 2017-12-05 15:16 UTC
Labels: help wanted
